name: flutter_app
description: "Glucose Blood Sugar Tracker by DrLogs TM"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  freezed: ^2.4.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  intl: ^0.20.2
  http: ^1.1.0
  provider: ^6.1.0
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  path_provider: ^2.1.1
  lottie: ^2.7.0
  google_fonts: ^6.2.1
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_local_notifications: ^19.0.0
  android_alarm_manager_plus: ^4.0.7
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  health: ^12.2.0
  uuid: ^4.3.3
  local_auth: ^2.3.0
  fl_chart: ^0.66.2
  pdf: ^3.11.3
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  objectbox_generator: ^2.3.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/meds.json
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
        - asset: fonts/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
        - asset: fonts/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: fonts/Poppins-SemiBoldItalic.ttf
    - family: FontAwesome6ProLight
      fonts:
        - asset: fonts/FontAwesome6Pro-Light-300.otf
    - family: FontAwesome6ProSolid
      fonts:
        - asset: fonts/FontAwesome6Pro-Solid-900.otf
